/**
 * ASCII Char Codes.
 */
export const enum CharCode {
  /** [space] */Space = 32,
  /** "\\t" */Tab = 9,
  /** "\\n" */Newline = 10,
  /** "\\r" */CarriageReturn = 13,
  /** "!" */ExclamationMark = 33,
  /** "\\"" */DoubleQuote = 34,
  /** "#" */NumberSign = 35,
  /** "$" */DollarSign = 36,
  /** "%" */PercentSign = 37,
  /** "&" */Ampersand = 38,
  /** "'" */SingleQuote = 39,
  /** "(" */LeftParen = 40,
  /** ")" */RightParen = 41,
  /** "*" */Asteris = 42,
  /** "+" */PlusSign = 43,
  /** "," */Comma = 44,
  /** "-" */Hyphen = 45,
  /** "." */Period = 46,
  /** "/" */Slash = 47,
  /** ":" */Colon = 58,
  /** ";" */Semicolon = 59,
  /** "<" */LessThan = 60,
  /** "=" */EqualsTo = 61,
  /** ">" */MoreThan = 62,
  /** "?" */QuestionMark = 63,
  /** "@" */AtSign = 64,
  /** "[" */LeftSquareBracket = 91,
  /** "\" */Backslash = 92,
  /** "]" */RightSquareBracket = 93,
  /** "^" */Caret = 94,
  /** "_" */Underscore = 95,
  /** "`" */GraveAccent = 96,
  /** "{" */LeftCurlyBrace = 123,
  /** "|" */VerticalBar = 124,
  /** "}" */RightCurlyBrace = 125,
  /** "~" */Tilde = 126,
}
